name: gfl
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11      # pick the 3.11.x series you need
  - numpy            # for array operations
  - scipy            # for linear algebra, I/O (scipy.io), sparse, and eigh
  - pillow           # for PIL.Image
  - matplotlib       # for plotting with plt
  - pip              # so you can still pip-install anything else

